data_folders:
   - test_data/hiseqx # HiSeqX

sample_sheet_path:
   hiseq:
      test_data/sample_sheets/hiseq
   hiseqx:
      test_data/sample_sheets/hiseqx
   miseq:
      test_data/sample_sheets/miseq

